//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietGoiY
    {
        public long MaGoiY { get; set; }
        public long MaSP { get; set; }
        public double Diem { get; set; }
    
        public virtual GoiY GoiY { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
