//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhSanPham
    {
        public long MaHinh { get; set; }
        public long MaSP { get; set; }
        public Nullable<long> MaBienThe { get; set; }
        public string TenHinh { get; set; }
        public Nullable<int> ThuTuHinh { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
