//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuKien()
        {
            this.ChiTietSuKienGoiYs = new HashSet<ChiTietSuKienGoiY>();
        }
    
        public long MaSuKien { get; set; }
        public Nullable<long> MaKH { get; set; }
        public string MaPhien { get; set; }
        public Nullable<long> MaSP { get; set; }
        public Nullable<long> MaBienThe { get; set; }
        public string LoaiSuKien { get; set; }
        public string GiaTri { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSuKienGoiY> ChiTietSuKienGoiYs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
